version: '3.7'

services:
  keuangan-fe:
    build: .
    image: 'atcho/keuangan-fe'
    container_name: keuangan-fe
    restart: always
    env_file:
      - .env
    ports:
      - '3100:3000'
    networks:
      - keuangan

networks:
  keuangan:
    external: true
